version: '2'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Naveen123$'
      MYSQL_USER: root
      MYSQL_PASSWORD: 'Naveen123'
    ports:
      - "3307:3306"

  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/blog-management"
    ports: 
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: blog_management_development
      DB_PASSWORD: 'Naveen123$'
      DB_HOST: db